Avoid leaving a dangling future when handling a rejection in JsPromise::to_future
neon-bindings/neon pull request #1008
Opened 2023-11-17 14:46 UTC by kjvalencik

Previously, Neon was creating a distinct promise chain for handling resolved promises in `JsPromise::to_future`. This is problematic because it causes an `unhandledRejection`, even though the user may be handling the error.

In other words, it was the equivalent of this JavaScript:

```js
const p = Promise.reject(new Error("oh, no!"));

p.then(() => console.log("Everything is good!"));
p.catch(() => console.log("Handled the error"));
```

```
Handled the error
/private/tmp/try-catch/foo.js:1
const p = Promise.reject(new Error("oh, no!"));
                         ^

Error: oh, no!
```

Instead, we `catch` first and chain the `then` off of that promise chain. `then` will be called unconditionally; however, since `state` is empty we can skip the remainder of the body. This is equivalent to the following JavaScript:

```js
let settled = false;

Promise
    .reject(new Error("oh, no!"))
    .catch(() => {
        settled = true;

        console.log("Handled the error")
    })
    .then(() => {
        if (!settled) {
            console.log("Everything is good!")
        }
    });
```

2023-11-20 17:08 UTC, kjvalencik commented
`.then` can take a rejection handler as a second argument. This is a somewhat simpler option.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#onrejected

Ideally, we also wouldn't need to create new `JsFunction` on each `to_future`, but the only alternative I can think of is `.bind(..)`.

2023-11-20 22:52 UTC, dherman requested changes
This looks like a good fix, but I like your idea of using the two-argument variant of `.then()` better.

2023-11-21 16:42 UTC, kjvalencik commented on crates/neon/src/handle/mod.rs
> +        *self
These changes are in a separate "clippy fixes" commit. CI is currently failing on `main` due to clippy improvements in latest Rust.

2023-11-27 17:37 UTC, dherman approved these changes
LGTM!

2023-11-27 17:39 UTC, merged